Value             ::= (Identifier ":")? (Object| Array| String| ((("true")| ("false")))| ("null")| Number| Reference)
Reference         ::= "@" Identifier
Object            ::= Identifier? "{" ((((Identifier ":"| (String) ":")) Value) "," (((Identifier ":"| (String) ":")) Value)*)? (",")? "}"
Array             ::= "[" (Value ("," Value)*)? (",")? "]"
Identifier        ::= ([A-Za-z_]) ([A-Za-z0-9_])*
HexDigit          ::= [0-9A-Fa-f]
StringSplit       ::= ("\\\r\n"| "\\\r"| "\\\n")
SQStringChar      ::= [^ ' \ #x0-#x1f ]
DQStringChar      ::= [^ " \ #x0-#x1f ]
String            ::= (SingleQuoteString| DoubleQuoteString)
SingleQuoteString ::= ['] (StringSplit| ("\\" ["'/\bfnrt])| ("\\u" (HexDigit HexDigit HexDigit HexDigit))| SQStringChar)* [']
DoubleQuoteString ::= ["] (StringSplit| ("\\" ["'/\bfnrt])| ("\\u" (HexDigit HexDigit HexDigit HexDigit))| DQStringChar)* ["]
Number            ::= (LiteralNumber| Infinitive| NaN)
Infinitive        ::= [+-]? ("Infinity"| "Inf")
NaN               ::= "NaN"
LiteralNumber     ::= ([+-])? (Digit+) ("." (Digit+))? ([eE] ([+-])? (Digit+))?
Digit             ::= [0-9]
Comment           ::= ("/*" (.)* "*/"| "//" (.)*)