Value             ::= (Identifier ":")? (Object| Array| String| ((("true")| ("false")))| ("null")| Number| Reference)
Reference         ::= "@" Identifier
Object            ::= Identifier? "{" ((((Identifier ":"| (String) ":")) Value) "," (((Identifier ":"| (String) ":")) Value)*)? (",")? "}"
Array             ::= "[" (Value ("," Value)*)? (",")? "]"
String            ::= ((['] (Escape| ([^ ' \ #x0-#x1f ]))* ['])| (["] (Escape| ([^ " \ #x0-#x1f ]))* ["]))
Escape            ::= (("\\u" (HexDigit HexDigit HexDigit HexDigit))| ("\\" ["'/\bfnrt])| (("\\" "\r\n"| "\\" "\r"| "\\" "\n")))
HexDigit          ::= [0-9A-Fa-f]
Number            ::= ((([+-])? "0x" HexDigit+)| (([+-])? (Digit+) ("." (Digit+))? ([eE] ([+-])? (Digit+))?)| ([+-]? ("Infinity"| "Inf"))| ("NaN"))
Digit             ::= [0-9]
Identifier        ::= ([A-Za-z_]) ([A-Za-z0-9_])*
Comment           ::= ("/*" (.)* "*/"| "//" (.)*)